### ISSUE TITLE
Are you serious about forking Guix?

### ISSUE THREAD

**Issue by wdkrnls** [leibniz-psychology/guix-zpid#16]
Hi,

Thank you for taking the time to package up and share Rstudio for Guix :). I was planning on adding your channel to my system, but then saw your warning in the readme that you couldn't guarantee things would work with the official guix system in the future. So, I am looking for your opinion whether that is still your plan (or not) and if so whether you think that the RStudio tools might be best moved to a separate dedicated channel?

Thanks again,
Kyle

**Comment by PromyLOPh** [comment]
Hey Kyle,

it’s not really a fork of guix. It’s merely a “pinned” version, which the
packages in this repository (including RStudio) are tested with. Usually they
work fine with the current HEAD as well. The plan is to eventually follow
upstream more closely, but for now I simply lack the time to do so.

Do you have a suggestion how to improve the statement in the README?

Cheers,
Lars

**Comment by wdkrnls** [comment]
Hi Lars,

Thanks for the clarification :)

Maybe phrase it as saying that no extensive testing has been done for versions of Guix newer than (or much before) the last time you pulled from Guix master. However, given that you do not intend to diverge from master and that you do plan on periodically sync'ing with it, it should usually be safe for Guix users to include in their configurations.

**Comment by PromyLOPh** [comment]
Hey,

> Maybe phrase it as saying that no extensive testing has been done for
> versions of Guix newer than (or much before) the last time you pulled from
> Guix master. However, given that you do not intend to diverge from master and
> that you do plan on periodically sync'ing with it, it should usually be safe
> for Guix users to include in their configurations.
how about “The packages in this repository are currently only tested with older
versions of Guix, namely the one present in
https://github.com/leibniz-psychology/guix. We try to sync with upstream
occasionally, but if something breaks in the meantime, please open an issue.
Whenever possible possible, packages will be upstreamed to Guix proper and
disappear from this channel once accepted.”

Lars

**Comment by wdkrnls** [comment]
That sounds great to me!
